# --- Енкодери ---
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- ZMK Studio ---
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n

# --- Bluetooth та Потужність ---
# Підвищена потужність сигналу (+8dBm)
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Назва клавіатури 
CONFIG_ZMK_KEYBOARD_NAME="Angri"

# --- Енергозбереження ---
# Перехід у стан очікування (5 хв) 
CONFIG_ZMK_IDLE_TIMEOUT=300000
# Увімкнення глибокого сну 
CONFIG_ZMK_SLEEP=y
# Перехід у глибокий сон (30 хв) 
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000

# --- Дисплей (OLED) ---
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_TICK_PERIOD_MS=1000
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Nice!OLED Віджети та залежності
# Примітка: працюють коректно на центральній (лівій) стороні
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA=y
CONFIG_NICE_OLED_WIDGET_HID_INDICATORS_LUNA_ONLY_CAPSLOCK=y

# --- RGB Підсвітка (Underglow) ---
# Обов'язкові залежності для нових версій Zephyr (виправляють помилку WS2812_STRIP)
CONFIG_LED=y
CONFIG_LED_STRIP=y
CONFIG_ZMK_RGB_UNDERGLOW=y
CONFIG_WS2812_STRIP=y

# Налаштування ефектів RGB 
CONFIG_ZMK_RGB_UNDERGLOW_ON_START=n
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_IDLE=y
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n 
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=20
CONFIG_ZMK_RGB_UNDERGLOW_EFF_START=0
